//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.02 at 01:28:47 PM EST 
//


package com.meng.parsing.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.meng.parsing.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Region_QNAME = new QName("", "region");
    private final static QName _PublishDate_QNAME = new QName("", "publish_date");
    private final static QName _Payload_QNAME = new QName("", "payload");
    private final static QName _Dedup_QNAME = new QName("", "dedup");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _OhRef_QNAME = new QName("", "oh_ref");
    private final static QName _Timestamp_QNAME = new QName("", "timestamp");
    private final static QName _SentId_QNAME = new QName("", "sent_id");
    private final static QName _Sent_QNAME = new QName("", "sent");
    private final static QName _PolarityConf_QNAME = new QName("", "polarity_conf");
    private final static QName _OpId_QNAME = new QName("", "op_id");
    private final static QName _DocLink_QNAME = new QName("", "doc_link");
    private final static QName _Polarity_QNAME = new QName("", "polarity");
    private final static QName _DocId_QNAME = new QName("", "doc_id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.meng.parsing.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Opholder }
     * 
     */
    public Opholder createOpholder() {
        return new Opholder();
    }

    /**
     * Create an instance of {@link Regions }
     * 
     */
    public Regions createRegions() {
        return new Regions();
    }

    /**
     * Create an instance of {@link PreSent }
     * 
     */
    public PreSent createPreSent() {
        return new PreSent();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Authors }
     * 
     */
    public Authors createAuthors() {
        return new Authors();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Payloads }
     * 
     */
    public Payloads createPayloads() {
        return new Payloads();
    }

    /**
     * Create an instance of {@link Opinion }
     * 
     */
    public Opinion createOpinion() {
        return new Opinion();
    }

    /**
     * Create an instance of {@link DocTitle }
     * 
     */
    public DocTitle createDocTitle() {
        return new DocTitle();
    }

    /**
     * Create an instance of {@link PostSent }
     * 
     */
    public PostSent createPostSent() {
        return new PostSent();
    }

    /**
     * Create an instance of {@link Topics }
     * 
     */
    public Topics createTopics() {
        return new Topics();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link OhRefs }
     * 
     */
    public OhRefs createOhRefs() {
        return new OhRefs();
    }

    /**
     * Create an instance of {@link Opinions }
     * 
     */
    public Opinions createOpinions() {
        return new Opinions();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publish_date")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPublishDate(String value) {
        return new JAXBElement<String>(_PublishDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "payload")
    public JAXBElement<String> createPayload(String value) {
        return new JAXBElement<String>(_Payload_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dedup")
    public JAXBElement<BigInteger> createDedup(BigInteger value) {
        return new JAXBElement<BigInteger>(_Dedup_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oh_ref")
    public JAXBElement<String> createOhRef(String value) {
        return new JAXBElement<String>(_OhRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timestamp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTimestamp(String value) {
        return new JAXBElement<String>(_Timestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sent_id")
    public JAXBElement<String> createSentId(String value) {
        return new JAXBElement<String>(_SentId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sent")
    public JAXBElement<String> createSent(String value) {
        return new JAXBElement<String>(_Sent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "polarity_conf")
    public JAXBElement<BigDecimal> createPolarityConf(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PolarityConf_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "op_id")
    public JAXBElement<String> createOpId(String value) {
        return new JAXBElement<String>(_OpId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "doc_link")
    public JAXBElement<String> createDocLink(String value) {
        return new JAXBElement<String>(_DocLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "polarity")
    public JAXBElement<BigInteger> createPolarity(BigInteger value) {
        return new JAXBElement<BigInteger>(_Polarity_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "doc_id")
    public JAXBElement<String> createDocId(String value) {
        return new JAXBElement<String>(_DocId_QNAME, String.class, null, value);
    }

}
