//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.02 at 01:28:47 PM EST 
//


package com.meng.parsing.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}op_id"/>
 *         &lt;element ref="{}sent_id"/>
 *         &lt;element ref="{}doc_id"/>
 *         &lt;element ref="{}doc_link"/>
 *         &lt;element ref="{}doc_title"/>
 *         &lt;element ref="{}dedup"/>
 *         &lt;element ref="{}payloads"/>
 *         &lt;element ref="{}timestamp"/>
 *         &lt;element ref="{}publish_date"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}pre_sent"/>
 *         &lt;element ref="{}sent"/>
 *         &lt;element ref="{}post_sent"/>
 *         &lt;element ref="{}topics"/>
 *         &lt;element ref="{}publisher"/>
 *         &lt;element ref="{}authors"/>
 *         &lt;element ref="{}opholder"/>
 *         &lt;element ref="{}oh_refs"/>
 *         &lt;element ref="{}polarity"/>
 *         &lt;element ref="{}polarity_conf"/>
 *         &lt;element ref="{}regions"/>
 *       &lt;/sequence>
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opId",
    "sentId",
    "docId",
    "docLink",
    "docTitle",
    "dedup",
    "payloads",
    "timestamp",
    "publishDate",
    "type",
    "preSent",
    "sent",
    "postSent",
    "topics",
    "publisher",
    "authors",
    "opholder",
    "ohRefs",
    "polarity",
    "polarityConf",
    "regions"
})
@XmlRootElement(name = "opinion")
public class Opinion {

    @XmlElement(name = "op_id", required = true)
    protected String opId;
    @XmlElement(name = "sent_id", required = true)
    protected String sentId;
    @XmlElement(name = "doc_id", required = true)
    protected String docId;
    @XmlElement(name = "doc_link", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String docLink;
    @XmlElement(name = "doc_title", required = true)
    protected DocTitle docTitle;
    @XmlElement(required = true)
    protected BigInteger dedup;
    @XmlElement(required = true)
    protected Payloads payloads;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String timestamp;
    @XmlElement(name = "publish_date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String publishDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlElement(name = "pre_sent", required = true)
    protected PreSent preSent;
    @XmlElement(required = true)
    protected String sent;
    @XmlElement(name = "post_sent", required = true)
    protected PostSent postSent;
    @XmlElement(required = true)
    protected Topics topics;
    @XmlElement(required = true)
    protected Publisher publisher;
    @XmlElement(required = true)
    protected Authors authors;
    @XmlElement(required = true)
    protected Opholder opholder;
    @XmlElement(name = "oh_refs", required = true)
    protected OhRefs ohRefs;
    @XmlElement(required = true)
    protected BigInteger polarity;
    @XmlElement(name = "polarity_conf", required = true)
    protected BigDecimal polarityConf;
    @XmlElement(required = true)
    protected Regions regions;
    @XmlAttribute(name = "index", required = true)
    protected BigInteger index;

    /**
     * Gets the value of the opId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpId() {
        return opId;
    }

    /**
     * Sets the value of the opId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpId(String value) {
        this.opId = value;
    }

    /**
     * Gets the value of the sentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentId() {
        return sentId;
    }

    /**
     * Sets the value of the sentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentId(String value) {
        this.sentId = value;
    }

    /**
     * Gets the value of the docId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocId() {
        return docId;
    }

    /**
     * Sets the value of the docId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocId(String value) {
        this.docId = value;
    }

    /**
     * Gets the value of the docLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocLink() {
        return docLink;
    }

    /**
     * Sets the value of the docLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocLink(String value) {
        this.docLink = value;
    }

    /**
     * Gets the value of the docTitle property.
     * 
     * @return
     *     possible object is
     *     {@link DocTitle }
     *     
     */
    public DocTitle getDocTitle() {
        return docTitle;
    }

    /**
     * Sets the value of the docTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocTitle }
     *     
     */
    public void setDocTitle(DocTitle value) {
        this.docTitle = value;
    }

    /**
     * Gets the value of the dedup property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDedup() {
        return dedup;
    }

    /**
     * Sets the value of the dedup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDedup(BigInteger value) {
        this.dedup = value;
    }

    /**
     * Gets the value of the payloads property.
     * 
     * @return
     *     possible object is
     *     {@link Payloads }
     *     
     */
    public Payloads getPayloads() {
        return payloads;
    }

    /**
     * Sets the value of the payloads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payloads }
     *     
     */
    public void setPayloads(Payloads value) {
        this.payloads = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishDate(String value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the preSent property.
     * 
     * @return
     *     possible object is
     *     {@link PreSent }
     *     
     */
    public PreSent getPreSent() {
        return preSent;
    }

    /**
     * Sets the value of the preSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreSent }
     *     
     */
    public void setPreSent(PreSent value) {
        this.preSent = value;
    }

    /**
     * Gets the value of the sent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSent(String value) {
        this.sent = value;
    }

    /**
     * Gets the value of the postSent property.
     * 
     * @return
     *     possible object is
     *     {@link PostSent }
     *     
     */
    public PostSent getPostSent() {
        return postSent;
    }

    /**
     * Sets the value of the postSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostSent }
     *     
     */
    public void setPostSent(PostSent value) {
        this.postSent = value;
    }

    /**
     * Gets the value of the topics property.
     * 
     * @return
     *     possible object is
     *     {@link Topics }
     *     
     */
    public Topics getTopics() {
        return topics;
    }

    /**
     * Sets the value of the topics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topics }
     *     
     */
    public void setTopics(Topics value) {
        this.topics = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link Publisher }
     *     
     */
    public Publisher getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Publisher }
     *     
     */
    public void setPublisher(Publisher value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthors(Authors value) {
        this.authors = value;
    }

    /**
     * Gets the value of the opholder property.
     * 
     * @return
     *     possible object is
     *     {@link Opholder }
     *     
     */
    public Opholder getOpholder() {
        return opholder;
    }

    /**
     * Sets the value of the opholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Opholder }
     *     
     */
    public void setOpholder(Opholder value) {
        this.opholder = value;
    }

    /**
     * Gets the value of the ohRefs property.
     * 
     * @return
     *     possible object is
     *     {@link OhRefs }
     *     
     */
    public OhRefs getOhRefs() {
        return ohRefs;
    }

    /**
     * Sets the value of the ohRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OhRefs }
     *     
     */
    public void setOhRefs(OhRefs value) {
        this.ohRefs = value;
    }

    /**
     * Gets the value of the polarity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPolarity() {
        return polarity;
    }

    /**
     * Sets the value of the polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPolarity(BigInteger value) {
        this.polarity = value;
    }

    /**
     * Gets the value of the polarityConf property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPolarityConf() {
        return polarityConf;
    }

    /**
     * Sets the value of the polarityConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPolarityConf(BigDecimal value) {
        this.polarityConf = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link Regions }
     *     
     */
    public Regions getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regions }
     *     
     */
    public void setRegions(Regions value) {
        this.regions = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

}
